### ISSUE TITLE
SUBACK fixed header flags (reserved bits) = subscription failure

### ISSUE THREAD

**Issue by azol** [hivemq/hivemq-mqtt-client#340] opened 2019-10-30 18:01 UTC
I get weird SUBACK from including Packet fixed header reserved bits set which causes hivemq-mqtt-client to fail. Unfortunately I can't change the server implementation. I'm not really sure but it should be ok to allow (ignore?) reserved bits usage. 

## Expected behavior

Successful SUBACK processing

## Actual behavior

System.err: com.hivemq.client.mqtt.exceptions.MqttSessionExpiredException: Session expired as connection was closed.
    Caused by: com.hivemq.client.mqtt.mqtt3.exceptions.Mqtt3DisconnectException: Exception while decoding SUBACK: fixed header flags must be 0 but were 2
    Caused by: com.hivemq.client.mqtt.exceptions.MqttDecodeException: Exception while decoding SUBACK: fixed header flags must be 0 but were 2

### Steps

Send SUBACK '100010010'

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.2
- Used JVM version: 11

**Comment by SgtSilvio** [comment] 2019-10-31 12:22
The MQTT specification states that it is a MUST to validate reserved bits:
> "The remaining bits [3-0] of byte 1 in the Fixed Header contain flags specific to each MQTT Control Packet type as shown below. Where a flag bit is marked as “Reserved”, it is reserved for future use and MUST be set to the value listed [MQTT-2.1.3-1]. If invalid flags are received it is a Malformed Packet. Refer to section 4.13 for details about handling errors." https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901023

So the broker you are using does not conform to the MQTT specification.
Which broker are you using?
You should file a bug there.

What we could do at the client side is adding a flag that turns off this validation.
By default the validation must be on, as we do not want to support specification violations.
The flag should not be part of the API, maybe use a system property.

**Comment by azol** [comment] 2019-11-07 16:21
we better close the issue. You are completely right. It's not our fault.

**Comment by MicWalter** [comment] 2019-11-08 20:18
Closing this issue, not an issue caused by the client.

**Closed by MicWalter** 2019-11-08 20:18 UTC
